import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    // Creating an object of the user's score that initially starts at zero
    userScore: {
      winPoints: 0,
      lossPoints: 0
    },

    // Creating an object of the computer's score that initially starts at zero
    computerScore: {
      winPoints: 0,
      lossPoints: 0,
    },

    // Creating a variable that represents the number of ties in the game and initially setting it to zero
    tiePoints: 0,

    // Creating an array of the three game options as strings
    rockPaperScissorsOptions: [
      "Rock",
      "Paper",
      "Scissors"
    ],

    // Creating an array of each game option image data as objects
    rockPaperScissorsImages: [
      {
        rockSrc: "https://www.kindpng.com/picc/m/266-2667213_transparent-rock-paper-scissors-clipart-clipart-rock-paper.png",
        rockAlt: "A clipart of a fist positioned to the left representing the symbol of a rock in the game 'rock, paper, scissors' that is styled with a white circular, black-bordered background."
      },
      {
        paperSrc: "https://www.clipartkey.com/mpngs/m/109-1094264_rock-paper-scissors-png.png",
        paperAlt: "A clipart of a open hand positioned to the left representing the symbol of a rock in the game 'rock, paper, scissors' that is styled with a white circular, black-bordered background."
      },
      {
        scissorsSrc: "https://www.clipartkey.com/mpngs/m/109-1094404_rock-paper-scissors-png.png",
        scissorsAlt: "A clipart of a hand creating the shape of a pair of scissors positioned to the left representing the symbol of a rock in the game 'rock, paper, scissors' that is styled  with a white circular, black-bordered background."
      }
    ],

    // Initializing an empty object to represent the user's selection and updating the values when the user clicks on one of the options
    userSelectionImage: {
      src: "",
      alt: ""
    },

    // Initializing an empty object to represent the computer's random selection and updating the value to whatever option the computer generates
    computerSelectionImage: {
      src: "",
      alt: ""
    },
  },

  mutations: {
    // Creating a function that will increase the user's win points by one if the user wins the game
    updateUserWinPoints: function(state) {
      state.userScore.winPoints++;
    },

    // Creating a function that will increase the user's loss points by one if the user loses the game
    updateUserLossPoints: function(state) {
      state.userScore.lossPoints++;
    },

    // Creating a function that will increase the computer's win points by one if the computer wins the game
    updateComputerWinPoints: function(state) {
      state.computerScore.winPoints++;
    },

    // Creating a function that will increase the computer's loss points by one if the computer loses the game
    updateComputerLossPoints: function(state) {
      state.computerScore.lossPoints++;
    },

    // Creating a function that will increase the number ties by one if the user and computer show the same options
    updateTiePoints: function(state) {
      state.tiePoints++;
    },

    // Creating a function that will update the image source to whatever option the user has selected
    updateUserImageLink: function(state, data) {
      state.userSelectionImage.src = data;
    },

    // Creating a function that will update the image description to whatever option the user has selected
    updateUserImageAlt: function(state, data) {
      state.userSelectionImage.alt = data;
    },

    // Creating a function that will update the image source to whatever option was generated by the computer
    updateComputerImageLink: function(state, data) {
      state.computerSelectionImage.src = data;
    },

    // Creating a function that will update the image description to whatever option was generated by the computer
    updateComputerImageAlt: function(state, data) {
      state.computerSelectionImage.alt = data;
    }
  },

  actions: {
  },
  getters: {
  }
})
